name: snap_journal
description: "A digital journal app with photos, entries, and notifications."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Data persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1

  # Icons
  cupertino_icons: ^1.0.8

  # Device features
  image_picker: ^1.1.2       # For gallery and camera access
  camera: ^0.11.0+2          # Full camera support
  flutter_local_notifications: ^17.2.3  # Local notifications
  intl: ^0.19.0   # 👈 add this line

  # State management
  provider: ^6.1.2

  # UI enhancements
  google_fonts: ^6.2.1       # Optional: Better typography
  uuid: ^4.1.0

  file_picker: ^8.1.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  record: ^6.1.2
  just_audio: ^0.10.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true